### ISSUE TITLE
来源文献

### ISSUE THREAD

**Issue by Light-young** [reled/BBS04#1]
请问这个是D Boneh等人的Short group signatures方案的实现吗

**Comment by reled** [comment]
是的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reled/BBS04"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月13日(星期三) 下午2:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[reled/BBS04] 来源文献 (Issue #1)





 
请问这个是D Boneh等人的Short group signatures方案的实现吗
